"""Add post_type to community_posts

Revision ID: 001
Revises: 
Create Date: 2026-02-06 06:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_posts', sa.Column('post_type', sa.String(length=50), nullable=False, server_default='Publicación General'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_posts', 'post_type')
    # ### end Alembic commands ###
